export const UPDATE_USERLIST = "UPDATE_USERLIST";
export const UPDATE_TIMESHEETS = "UPDATE_TIMESHEETS";
export const USERLIST = "USERLIST";
export const TIMESHEETS = "TIMESHEETS";
export const DO_CLOCKIN = "DO_CLOCKIN";
export const DEVICE_USERLIST = "DEVICE_USERLIST";
