// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:3f00dfaf-372e-4c4d-82e1-1f7e3da0357e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_6VPY3XZWO",
    "aws_user_pools_web_client_id": "20fvfk90ur5gh05rk7hdp2rpi2"
};


export default awsmobile;
