// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_cognito_identity_pool_id:
    'us-east-1:55a80482-32f5-495e-b275-17c5a047c465',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_tm4nMDZy0',
  aws_user_pools_web_client_id: '3phof9nbljn97usdtk3g31m7jk',
  aws_user_files_s3_bucket: 'andrewsstorage',
  aws_user_files_s3_bucket_region: 'us-east-1',
  aws_appsync_graphqlEndpoint:
    'https://23bbzifdbfdtddyqzuhh6ry25e.appsync-api.us-east-1.amazonaws.com/graphql',
  aws_appsync_region: 'us-east-1',
  aws_appsync_authenticationType: 'API_KEY',
  aws_appsync_apiKey: 'da2-fovoifzzzrbuzb5jxetpkfiyqa',
  aws_cloud_logic_custom: [
    {
      name: 'employeesRest',
      endpoint: 'https://f3agj46vb4.execute-api.us-east-1.amazonaws.com/Prod',
      region: 'us-east-1',
      apiKey: 'Dp6JO2Naba7w5B3k7vhi430e2eOI9H0Y8GGROU11',
    },
    {
      name: 'employeesRest',
      endpoint: 'https://f3agj46vb4.execute-api.us-east-1.amazonaws.com/Prod',
      region: 'us-east-1',
    },
  ],
}

export default awsmobile
